CREATE DATABASE IF NOT EXISTS `RENTING`;
USE RENTING;
#DROP TABLE `full`;
CREATE TABLE IF NOT EXISTS `full`(
    `sImeiID`	    varchar(30),
    `sPlatName`	    varchar(100),
    `sPlatType`	    varchar(100),
    `sActionName`	varchar(200),
    `sContentType`	varchar(200),
    `iPV`           bigint(11),
    `sVisitDate`	DATE,
    `sVisitTime`	varchar(30),
    `sVProvince`	varchar(30),
    `sVCity`	    varchar(30),
    `sVRegion`	    varchar(100),
    `sPropName`	    varchar(500),
    `sLoupan`	    varchar(250),
    `sAvgPrice`	    decimal(6,1),
    `sTotalPrice`	decimal(8,1),
    `sLayout`	    varchar(200),
    `sArea`	        decimal(6,1),
    `sToward`	    varchar(200),
    `sFloor`	    varchar(200),
    `sFitment`	    varchar(200),
    `sAge`	        varchar(500),
    `sBuildType`	varchar(200),
    `sStruct`	    varchar(200),
    `sHouseType`	varchar(200),
    `sPropType`		varchar(200),
    `sBrokerName`	varchar(1000),
    `sBrokerPhone`	bigint(11),
    `sBrokerCompany` varchar(1000),
    `sRentMode`	    varchar(200),
    `sAddress`	    varchar(1000),
    `sLng`	        float,
    `sLat`	        float,
    `sDate`		    DATE,
    `sProvince`		varchar(30),
    `sCity`		    varchar(30),
    `sZoneCode`		int(5),
    `sSpiderID`	    varchar(200),
    `sSystem`		varchar(30),
    `sIdfa`		    varchar(50),
    `sBestTime`		varchar(100)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
SELECT * FROM `full` LIMIT 100;
